config/routes.rb
Rails.application.routes.draw do
  resources :tasks, only: %i[index] do
    resource :finish_state, only: %i[create destroy], module: :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  scope :default_order, -> { order(:id) }
  scope :finished, -> { where(finished: true) }
  scope :unfinished, -> { where(finished: false) }

  def finish!
    update!(finished: true)
  end

  def unfinish!
    update!(finished: false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks/application_controller.rb
class Tasks::ApplicationController < ApplicationController
  before_action :set_nested_task

  private

  def set_nested_task
    @task = Task.find(params[:task_id])
  end
end

app/controllers/tasks/finish_states_controller.rb
class Tasks::FinishStatesController < Tasks::ApplicationController
  protect_from_forgery with: :null_session

  def create
    @task.finish!
  end

  def destroy
    @task.unfinish!
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.default_order
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTodoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_task_list.html.slim
ul.list-group.list-group-flush.px-3
  - tasks.each do |task|
    li.list-group-item
      input.form-check-input.js-task-checkbox(id="task-checkbox-#{task.id}" type="checkbox" checked=(task.finished?) data-url="#{task_finish_state_path(task)}")
      label(for="task-checkbox-#{task.id}")= task.title

app/views/tasks/finish_states/_refresh_task_lists.js.erb
$('#js-unfinished-task-list').html('<%= j render 'tasks/task_list', tasks: Task.default_order.unfinished %>')
$('#js-finished-task-list').html('<%= j render 'tasks/task_list', tasks: Task.default_order.finished %>')

app/views/tasks/finish_states/create.js.erb
<%= render 'refresh_task_lists' %>

app/views/tasks/finish_states/destroy.js.erb
<%= render 'refresh_task_lists' %>

app/views/tasks/index.html.slim
section.container.pt-5
  .row
    .col-6
      .card
        .card-header やること
        #js-unfinished-task-list
          = render 'tasks/task_list', tasks: @tasks.unfinished
    .col-6
      .card
        .card-header やったこと
        #js-finished-task-list
          = render 'tasks/task_list', tasks: @tasks.finished